travis:
  secure:
    BINSTAR_TOKEN: BEcrChuV7YYFaygZhMRs1Gk/5mS71BbIowCUmvetlFO+yi6M1/wbAsuIjCz9cLVYhpK5HCIML65Tb6MAhH4hQng6bsRW1+uVpsv/WY5D/CLnVXgj7uJf/WZXUvurUyhcumqrpA+6m6JxXXKbEHjrRGqpyTzTLdIll0K4Af+ZqN2N7p8F8u4sqHp57WDuTgzvqfbXjJMV1e7fPd8E/2pbTKd5XqcJ2dfDcsDoKE9WlF+M8Q00NEnBV0aZDdNygwSXG3W0Jsl6javo2g6nrCHy5WGkED1gb9TaKQN9+zM7DBrFljzVL7LeAkB7zYdTkwQyYNGeWQLBVrLKONV52LroLMsST44lTLovsnPjZPPTiTHh4zo4dNpLovHCucU24Jf3pScrTnPtXTX6D0b54BsLDGTeA4B++e0uQHBBqpmEvjNidMotxbgKWU+bdC5EHTvYZ1+UtlvgF09rcANODmryegw269V97NhiFWQoGpgfOVE5ENTvD1EHVWD8/86uY3YLCx9Wkh4HUFA22WjkgY3/84kslbsEQx+U0Yc2mAhStvJRqHGLupQJv13d13CNiDJhgmhBOm2DiTwIpir/jd20gQWHThCPkX7bx1Jis5MlnD5Riw0b+4e8+aQXSpMF8WTNZAjCMULaSqn6P2tMsfFkYcbFgcibrRzMpqWQ/4F71UY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
