travis:
  secure:
    BINSTAR_TOKEN: GBgLUP3fjS0yHBEmdPF2+P6y7Z0F0ZzypnNfOvWz9rrDwBWUtXwDA5HH7GxEDmOQyCtnMmRRtJJSYM5W2on353tr85knKhuuQ08SAGNEjsFSXvBETtSdTt3A0CUsLlzBAG+CPvZWUvs0qQ1TKXdB/f4nhFLNawpyOBeo1j1kqBRL9qhIGzJolM99wmnJeTSF4QmXnPG2lnjqeJFb7L0IRMdeJ/hmpfyZ3G+qnPaJT3HcdqeQabbGqxkL6zfnIDOaW/J3fco88oABlMq7ml8AulGh+PI1DYwk09LOXkbDLY7SvBRwVOYuVB2QdgrA+rG+7ds8EVFBj76eate9EoaOuyOFSfWE/dTDw3F7V1kJZBJDJbHqfrZCnxDfUieugdVO+XKApmV0eqURAU7AHhjGyKdvnRbD83SoO1zaGCE1hrK1h3I/KXM/6v/C/6Ei8MS3QyegkD7jQHhcCDfZUIqPlb+HEfpcb1Mg3DLqJ9UUkLOzjVsVt3dtOWRcl2qny1ZQtl2dY6HQKIeQgmhyP1gR59DkKqwQzaW761tlRESmYASdN24iCRojMbLTXhE4jyfqISdM3adHh+5TmEopCWNjDKEprompU2IMOJo5Ur72HtzhKdCKi1Rhcv3OZZoG14OHqAGjUCYzL9Zj0JNK/6lXk1GzgqubGlooLxIQ1A29DrQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
